services:
  obscreen:
    image: obscreen/obscreen:latest
    pull_policy: always
    container_name: obscreen
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./obscreen.lic:/app/obscreen.lic
      - ./data:/app/data
    environment:
      DEBUG: "false"
      PORT: 5000
      SECRET_KEY: ANY_SECRET_KEY_HERE
